openapi: '3.0.0'
info:
  version: 0.1.0
  title: Example Web API
servers:
- url: /api
tags:
- name: my tag
  description: |
    This is my special tag
- name: extra tag
  description: |
    Newly added endpoints
paths:
  /helloMessage:
    get:
      summary: Get hello message from server
      operationId: getHelloMessage
      tags:
      - my tag
      description: |
        Get a special, unique hello message from the server
      parameters:
      - name: name
        in: query
        required: true
        description: |
          Send your name so the server can say hello
        schema:
          type: string
      responses:
        '200':
          description: Hello message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloMessage'
        default:
          $ref: '#/components/responses/UnexpectedError'
  /visitorBook:
    get:
      summary: Get all the names in the visitor book
      operationId: getVisitorBook
      tags:
      - extra tag
      description: Return all names in the visitor book
      responses:
        '200':
          description: Names in the visitor book returned
          content:
            application/json:
              schema:
                required:
                - visitors
                properties:
                  visitors:
                    type: array
                    items:
                      type: string
                      example: 'Visitor'
        default:
          $ref: '#/components/responses/UnexpectedError'
    post:
      summary: Sign visitor book with my name
      operationId: signVisitorBook
      tags:
      - my tag
      description: |
        Send your name to add it to the list of previous visitors
      requestBody:
        description: |
          Revision descriptor for the indexed revision and the base revision to use for the delta.
        required: true
        content:
          application/json:
            schema:
              required:
              - name
              properties:
                name:
                  type: string
                  example: 'Visitor'
      responses:
        '200':
          description: Visitor book signed
          content:
            application/json:
              schema:
                required:
                - visitors
                properties:
                  visitors:
                    type: array
                    items:
                      type: string
                      example: 'Visitor'
        default:
          $ref: '#/components/responses/UnexpectedError'
    delete:
      summary: Delete visitor book
      operationId: clearVisitorBook
      responses:
        '200':
          description: Visitor book cleared
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
        default:
          $ref: '#/components/responses/UnexpectedError'
#  /visitorBook/{visitorName}:
#    delete:
#      summary: Delete name from visitor book
#      operationId: deleteNameFromVisitorBook
#      parameters:
#      - in: path
#        name: visitorName
#        schema:
#          type: string
#        required: true
#        description: name of the visitor to remove from visitor book
#      responses:
#        '200':
#          description: Name removed from visitor book
#        default:
#          $ref: '#/components/responses/UnexpectedError'


components:
  responses:
    UnexpectedError:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    HelloMessage:
      required:
      - message
      properties:
        message:
          type: string
          example: 'Hello OpenAPI'
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: 'Exception occurred during request processing'